### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by LoseYouNow** [KisSsArt/CS2-Cheat-Base#8]
when you inject the dll and join the team , the game will crash,caused by the SDL2.dll

**Comment by gr1ndy** [comment]
https://github.com/KisSsArt/CS2-Cheat-Base/blob/268afbfc166b190ae45f32e19c276e6bcb026e03/Cheat-Base/Source/Memory/Memory.cpp#L12 
just rename this to sdl3.dll
